### ISSUE TITLE
同学，作业１２．８截止啦，你赶紧提交呀啊啊啊啊啊啊啊啊啊啊

### ISSUE THREAD

**Issue by lynn0909** [Moon0shang/NSGA_II_homework#1]
啊啊啊啊啊啊啊啊

**Comment by Moon0shang** [comment]
哈哈哈哈哈哈，突然看见，诶，还有两个月，不急[滑稽]

**Comment by Moon0shang** [comment]
> 啊啊啊啊啊啊啊啊

哈哈哈哈哈哈，突然看见，诶，还有两个月，不急[滑稽]

**Comment by lynn0909** [comment]
哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈去年的12月8


 
---原始邮件---
发件人: "Yuanquan Xu"<notifications@github.com&gt;
发送时间: 2019年10月14日(星期一) 中午11:22
收件人: "Moon0shang/NSGA_II_homework"<NSGA_II_homework@noreply.github.com&gt;;
抄送: "Ｌingling Shi"<1921776352@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Moon0shang/NSGA_II_homework] 同学，作业１２．８截止啦，你赶紧提交呀啊啊啊啊啊啊啊啊啊啊 (#1)


 
啊啊啊啊啊啊啊啊
  
哈哈哈哈哈哈，突然看见，诶，还有两个月，不急[滑稽]

**Comment by Moon0shang** [comment]
> 哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈哈去年的12月8
> […](#)
> ---原始邮件--- 发件人: "Yuanquan Xu"<notifications@github.com&gt; 发送时间: 2019年10月14日(星期一) 中午11:22 收件人: "Moon0shang/NSGA_II_homework"<NSGA_II_homework@noreply.github.com&gt;; 抄送: "Ｌingling Shi"<1921776352@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题: Re: [Moon0shang/NSGA_II_homework] 同学，作业１２．８截止啦，你赶紧提交呀啊啊啊啊啊啊啊啊啊啊 (#1) 啊啊啊啊啊啊啊啊 哈哈哈哈哈哈，突然看见，诶，还有两个月，不急[滑稽] — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

有点意思哈，follow一波~
